config/routes.rb
Rails.application.routes.draw do
  resources :test_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  namespace :api do
    get '/test/index' ,to: 'testuser#index'
  end

  scope :user do
    post '/sign',to:'users#getSign'
    post '/invite',to: 'users#invite'

    post '/login', to: 'users#create'
    post '/read',to: 'users#read'
    post '/collect',to: 'users#collect'
    post '/article', to: 'users#article'

    post '/article/add',to:'wearticle#create'
    post '/article/delete',to:'wearticle#delete'


    post '/article/read',to: 'wearticle#read'
    post '/article/agree',to: 'wearticle#agree'
    post '/article/collect',to: 'wearticle#collect'



    ## 用户评论的添加和删除
    post '/article/comment/index',to: 'comment#create'
    post '/article/comment/delete',to: 'comment#delete'


    get '/rotate/index',to: 'frotate#get'
  end

  scope :article do
    # 获取文章接口
    post '/recom',to: 'wearticle#recommend'
    post '/all',to:'wearticle#index'
    post 'search',to:'wearticle#search'
  end

  scope :super do
    # 获取全部用户信息
    get '/user/all', to: 'super#user'
    # 获取某个用户信息
    get '/user/one', to: 'super#oneUser'


    get '/index', to: 'super#index'
    # get '/index', to: 'super#index'

    get '/create',to: 'super#create'
    get '/login',to: 'super#login'

    ## 删除某个用户
    get '/user/delete',to: 'super#delete'
    get '/article/delete', to: 'super#article'
    get '/comment',to: 'super#comment'


    ## 文章加为精华帖
    get '/article/elite',to: 'super#elite'
    ## 添加文章
    get '/article/add',to: 'super#addArticle'

    ## 添加轮播图信息
    get '/rotate/add',to:'frotate#add'
    get '/rotate/index',to: 'frotate#index'

  end


  scope :camp do
    get '/index',to: 'camps#create'
    get '/all',to:'camps#all'
    get '/answer/add',to: 'camps#answer'
    get '/user/add',to: 'camps#addUser'
    get '/user/all',to: 'camps#user'


    # match  '*qtcode',to: 'camps#qtcode',via: [:options,:post]
    # post  '/qtcode/add',to: 'camps#qtcode',via: [:options]

    post '/wechat/answer/all',to: 'camps#weall'
  end



end

app/models/test_user.rb
class TestUser
  include Mongoid::Document
  field :name, type: String
end

app/controllers/test_users_controller.rb
class TestUsersController < ApplicationController
  skip_before_action :verify_authenticity_token,:only => [:create]
  before_action :set_test_user, only: [:show, :edit, :update, :destroy]

  # GET /test_users
  # GET /test_users.json
  def index
    @test_users = TestUser.all
  end

  # GET /test_users/1
  # GET /test_users/1.json
  def show
  end

  # GET /test_users/new
  def new
    @test_user = TestUser.new
  end

  # GET /test_users/1/edit
  def edit
  end

  # POST /test_users
  # POST /test_users.json
  def create
    @test_user = TestUser.new(test_user_params)

    respond_to do |format|
      if @test_user.save
        format.html { redirect_to @test_user, notice: 'Test user was successfully created.' }
        format.json { render :show, status: :created, location: @test_user }
      else
        format.html { render :new }
        format.json { render json: @test_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_users/1
  # PATCH/PUT /test_users/1.json
  def update
    respond_to do |format|
      if @test_user.update(test_user_params)
        format.html { redirect_to @test_user, notice: 'Test user was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_user }
      else
        format.html { render :edit }
        format.json { render json: @test_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_users/1
  # DELETE /test_users/1.json
  def destroy
    @test_user.destroy
    respond_to do |format|
      format.html { redirect_to test_users_url, notice: 'Test user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_user
      @test_user = TestUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_user_params
      params.require(:test_user).permit(:name)
    end
end

app/helpers/test_users_helper.rb
module TestUsersHelper
end

app/views/test_users/_form.html.erb
<%= form_with(model: test_user, local: true) do |form| %>
  <% if test_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_user.errors.count, "error") %> prohibited this test_user from being saved:</h2>

      <ul>
      <% test_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/test_users/edit.html.erb
<h1>Editing Test User</h1>

<%= render 'form', test_user: @test_user %>

<%= link_to 'Show', @test_user %> |
<%= link_to 'Back', test_users_path %>

app/views/test_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_users.each do |test_user| %>
      <tr>
        <td><%= test_user.name %></td>
        <td><%= link_to 'Show', test_user %></td>
        <td><%= link_to 'Edit', edit_test_user_path(test_user) %></td>
        <td><%= link_to 'Destroy', test_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test User', new_test_user_path %>

app/views/test_users/new.html.erb
<h1>New Test User</h1>

<%= render 'form', test_user: @test_user %>

<%= link_to 'Back', test_users_path %>

app/views/test_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @test_user.name %>
</p>

<%= link_to 'Edit', edit_test_user_path(@test_user) %> |
<%= link_to 'Back', test_users_path %>